import { createFileRoute } from "@tanstack/react-router";
import { BadgeCheck, BrainCircuit, BriefcaseBusiness, History, ScanSearch } from "lucide-react";
import { PageHeading } from "@/components/page-heading";
import lawyerPortrait from "@/assets/lawyer-portrait.jpg";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [
  { title: "درباره هومن کریمی | وکیل پایه یک دادگستری" }, { name: "description", content: "آشنایی با هومن کریمی، وکیل پایه یک دادگستری با ۲۲ سال سابقه." },
  { property: "og:title", content: "درباره هومن کریمی" }, { property: "og:description", content: "وکیل پایه یک دادگستری با ۲۲ سال سابقه و پروانه شماره ۱۰۲۶۳." }, { property: "og:type", content: "profile" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: AboutPage });

const features=[[History,"۲۲ سال سابقه","تجربه مستمر در پیگیری پرونده‌های حقوقی"],[BriefcaseBusiness,"تجربه متنوع","رسیدگی به طیف متنوعی از دعاوی و اختلافات"],[BrainCircuit,"تحلیل دقیق","مطالعه جزئیات و انتخاب راهکار متناسب با هر پرونده"],[ScanSearch,"پیگیری مستمر","اطلاع‌رسانی منظم و همراهی تا پایان مسیر"]] as const;
function AboutPage(){return <><PageHeading eyebrow="درباره وکیل" title="هومن کریمی؛ همراه حقوقی شما" description="تجربه طولانی زمانی ارزشمند است که با دقت، صداقت و مسئولیت‌پذیری در کنار موکل قرار گیرد."/><section className="py-20"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-[0.8fr_1.2fr] lg:items-center lg:px-8"><div className="relative"><img src={lawyerPortrait} width={1200} height={1504} loading="lazy" alt="پرتره رسمی هومن کریمی" className="aspect-[4/5] w-full object-cover"/><div className="absolute -bottom-5 left-4 right-4 flex items-center gap-3 bg-primary p-5 text-primary-foreground sm:left-8 sm:right-auto"><BadgeCheck className="size-8 text-gold"/><div><strong className="block">شماره پروانه ۱۰۲۶۳</strong><span className="text-sm text-primary-foreground/60">از سال ۱۳۸۳</span></div></div></div><div><p className="text-sm font-bold text-gold-dark">وکیل پایه یک دادگستری</p><h2 className="mt-3 text-3xl font-black leading-tight text-primary sm:text-4xl">تجربه در خدمت تصمیم‌های حقوقی سنجیده</h2><div className="mt-7 space-y-5 leading-9 text-muted-foreground"><p>هومن کریمی، وکیل پایه یک دادگستری، فعالیت حرفه‌ای خود را از سال ۱۳۸۳ آغاز کرده و طی ۲۲ سال در حوزه‌های مختلف دعاوی حقوقی، کیفری، ملکی و خانواده به ارائه خدمات وکالت و مشاوره پرداخته است.</p><p>در رویکرد حرفه‌ای ایشان، شناخت دقیق موضوع، بررسی کامل اسناد و توضیح شفاف مسیر پرونده به موکل، پایه تصمیم‌گیری حقوقی است. هر پرونده با توجه به شرایط ویژه خود تحلیل می‌شود و راهکار پیشنهادی بر اساس منافع و حقوق موکل شکل می‌گیرد.</p><p>تعهد به محرمانگی، پاسخ‌گویی و پیگیری منظم، اصول ثابت همکاری با موکلان است.</p></div></div></div></section><section className="bg-surface py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-black text-primary">ویژگی‌های شاخص</h2><div className="mt-10 grid gap-px bg-border md:grid-cols-4">{features.map(([Icon,title,desc])=><article key={title} className="bg-background p-7"><Icon className="size-7 text-gold-dark"/><h3 className="mt-5 text-lg font-black text-primary">{title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{desc}</p></article>)}</div></div></section></>}