import { createFileRoute } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { CheckCircle2, Clock3, Mail, MapPin, Phone } from "lucide-react";
import { PageHeading } from "@/components/page-heading";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

export const Route = createFileRoute("/contact")({ head: () => ({ meta: [
  { title: "تماس با دفتر وکیل هومن کریمی" }, { name: "description", content: "اطلاعات تماس و نشانی دفتر وکیل هومن کریمی در نیاوران تهران." },
  { property: "og:title", content: "تماس با دفتر وکیل هومن کریمی" }, { property: "og:description", content: "نشانی، تلفن‌ها، ساعات کاری و فرم تماس دفتر نیاوران." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: ContactPage });

function ContactPage(){const [done,setDone]=useState(false);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setDone(true)}return <><PageHeading eyebrow="ارتباط با دفتر" title="تماس با ما" description="برای دریافت وقت مشاوره یا طرح پرسش اولیه، از راه‌های زیر با دفتر در ارتباط باشید."/><section className="py-20"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-[0.8fr_1.2fr] lg:px-8"><aside><h2 className="text-2xl font-black text-primary">اطلاعات دفتر</h2><div className="mt-8 space-y-6">{[[MapPin,"نشانی","تهران-نیاوران-مجتمع تجاری اداری نیاوران سنتر-واحد۳۰۴"],[Phone,"تلفن‌ها","۰۹۱۲۱۰۹۴۰۸۲ | ۰۲۱-۹۱۰۱۳۶۸۶"],[Mail,"ایمیل","info@homayounkarimi.com"],[Clock3,"ساعات کاری","شنبه تا چهارشنبه، ۹ تا ۱۸"]].map(([Icon,label,value])=><div key={label as string} className="flex gap-4"><span className="grid size-11 shrink-0 place-items-center bg-primary text-gold"><Icon className="size-5"/></span><div><h3 className="text-sm font-bold text-primary">{label as string}</h3><p className="mt-1 text-sm leading-7 text-muted-foreground">{value as string}</p></div></div>)}</div><div className="mt-10 overflow-hidden border border-border"><iframe title="نقشه نیاوران تهران" src="https://www.google.com/maps?q=Niavaran%20Center%20Tehran&output=embed" className="h-72 w-full" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></aside><div className="bg-surface p-7 sm:p-10"><h2 className="text-2xl font-black text-primary">ارسال پیام</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">فرم را تکمیل کنید تا برای بررسی اولیه با شما تماس گرفته شود.</p>{done?<div className="mt-10 grid min-h-80 place-items-center text-center"><div><CheckCircle2 className="mx-auto size-14 text-gold-dark"/><h3 className="mt-5 text-xl font-black text-primary">پیام شما ثبت شد</h3><p className="mt-3 text-muted-foreground">در اولین فرصت با شما تماس خواهیم گرفت.</p></div></div>:<form onSubmit={submit} className="mt-8 grid gap-5"><label className="grid gap-2 text-sm font-bold">نام<Input required placeholder="نام و نام خانوادگی"/></label><label className="grid gap-2 text-sm font-bold">تلفن<Input required inputMode="tel" placeholder="شماره تماس"/></label><label className="grid gap-2 text-sm font-bold">موضوع<Input required placeholder="موضوع پیام"/></label><label className="grid gap-2 text-sm font-bold">پیام<Textarea required className="min-h-36" placeholder="پیام خود را بنویسید"/></label><Button type="submit" size="lg">ارسال پیام</Button></form>}</div></div></section></>}