import { createFileRoute } from "@tanstack/react-router";
import { ArrowLeft, Play } from "lucide-react";
import { PageHeading } from "@/components/page-heading";
import { articles } from "@/lib/site-data";
import articleImage from "@/assets/legal-articles.jpg";

export const Route = createFileRoute("/magazine")({ head: () => ({ meta: [
  { title: "مقالات و ویدیوهای حقوقی | هومن کریمی" }, { name: "description", content: "مطالب آموزشی و اخبار حقوقی به زبان روشن و کاربردی." },
  { property: "og:title", content: "مقالات و ویدیوهای حقوقی | هومن کریمی" }, { property: "og:description", content: "مطالب آموزشی و اخبار حقوقی به زبان روشن و کاربردی." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: MagazinePage });

function MagazinePage() { return <><PageHeading eyebrow="دانشنامه حقوقی" title="مقالات و ویدیوها" description="پاسخ‌هایی روشن برای پرسش‌های متداول حقوقی و نکاتی که پیش از تصمیم‌گیری باید بدانید."/><section className="py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><article className="grid overflow-hidden bg-primary text-primary-foreground lg:grid-cols-2"><img src={articleImage} width={1408} height={912} alt="اسناد و ترازوی عدالت" className="h-full min-h-80 w-full object-cover"/><div className="flex flex-col justify-center p-8 lg:p-12"><span className="text-sm font-bold text-gold">مطلب منتخب</span><h2 className="mt-4 text-3xl font-black leading-snug">پیش از امضای قرارداد ملکی به چه نکاتی توجه کنیم؟</h2><p className="mt-5 leading-8 text-primary-foreground/70">مروری کاربردی بر بندهای مهم قرارداد و راه‌های کاهش ریسک اختلافات ملکی.</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-gold">خواندن مقاله <ArrowLeft className="size-4"/></span></div></article><div className="mt-14 grid gap-6 md:grid-cols-2">{articles.map((article,index)=><article key={article.title} className="border-b border-border py-7"><div className="flex items-center gap-3 text-xs font-bold text-gold-dark"><span>{article.category}</span><span className="size-1 rounded-full bg-border"/><span className="text-muted-foreground">{article.time}</span></div><h2 className="mt-4 text-xl font-black leading-8 text-primary">{article.title}</h2><p className="mt-3 leading-7 text-muted-foreground">{article.description}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary">خواندن بیشتر <ArrowLeft className="size-4"/></span></article>)}</div><div className="mt-20 border border-gold/30 bg-surface p-8 sm:flex sm:items-center sm:justify-between"><div><div className="flex items-center gap-3 text-gold-dark"><Play className="size-5"/><span className="text-sm font-bold">ویدیوهای حقوقی</span></div><h2 className="mt-3 text-2xl font-black text-primary">توضیح ساده موضوعات پیچیده حقوقی</h2><p className="mt-3 text-sm text-muted-foreground">ویدیوهای آموزشی این بخش به‌زودی منتشر می‌شوند.</p></div></div></div></section></> }